version: '3.8'
services:
  VkParsingNews:
    build: ./
    image: telegrambot
    container_name: TGBot
    ports:
      - "8080:8080"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
